# Generated by Django 4.1.3 on 2022-12-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("company_name", models.CharField(max_length=100)),
                ("email_name", models.CharField(max_length=100)),
                ("Phone_number", models.CharField(max_length=10)),
                ("subject_name", models.CharField(max_length=100)),
                ("password", models.CharField(blank=True, max_length=500, null=True)),
                ("address", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
