# Generated by Django 4.1.3 on 2022-12-15 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person", old_name="address", new_name="Address",
        ),
        migrations.RenameField(
            model_name="person", old_name="company_name", new_name="Company_name",
        ),
        migrations.RenameField(
            model_name="person", old_name="email_name", new_name="Email_name",
        ),
        migrations.RenameField(
            model_name="person", old_name="password", new_name="Password",
        ),
        migrations.RenameField(
            model_name="person", old_name="subject_name", new_name="Subject_name",
        ),
    ]
